### ISSUE TITLE
the application cant launch

### ISSUE THREAD

**Issue by soulaimaneB** [mwpenny/GameDroid#1]
how i can resolve this issues
the application cant launch in my smartphone 

![38421321_2075077972527005_3375854615462412288_n](https://user-images.githubusercontent.com/26674521/43680636-c667d34a-9836-11e8-8bd7-1d0acec09d51.png)

**Comment by mwpenny** [comment]
The app is working as expected. You just don't have any ROMs on your device. GameDroid does not come with any game files (copyrighted). Follow the instructions and place ROM files in the appropriate directory.

**Comment by mwpenny** [comment]
Additionally, this application was created in a few short months as part of a student project. As such, it lacks certain features like sound and proper frame limiting. I will likely come back to it and improve it when I have more free time but for now I'd recommend something else for day-to-day use if your plan is to simply play games and not to fork/modify it. The purpose of publishing on GitHub was to simply showcase the work that we did.

What is your use case?
