### ISSUE TITLE
Is this yours?

### ISSUE THREAD

**Issue by azumukupoe** [mwpenny/GameDroid#2]
https://play.google.com/store/apps/details?id=vgbapaid.gamedroid

**Comment by mwpenny** [comment]
Yes it is, thanks for pointing this out. This person is violating the license. They previously had the app up on the North American play store and removed it after I sent a message. Looks like I need to send another. This seems to happen pretty frequently.

**Comment by mwpenny** [comment]
This is a very late resolution, but the app is removed from the play store. Thanks again for bringing this up. I'm thinking of polishing it up and just publishing a free "definitive" version myself.
